
hydra:
  run:
    dir: ./
  output_subdir: 

general:
  workdir: ${hydra:runtime.cwd}  # where the code is executed
  datadir: ${general.workdir}/data
  image_folder: ${general.datadir}/images
  resized_images: ${general.datadir}/resized_images 

arg:
  newsize1: 100
  newsize2: 100


 