
hydra:
  run:
    dir: ./
  output_subdir: 

general:
  workdir: ${hydra:runtime.cwd}  # where the code is executed
  datadir: ${general.workdir}/data
  file_path: /Users/navjotsingh/Pipeline-Prep/tutorials/pipeline_demo/sample.jpeg

arg:
  newsize1: 200
  newsize2: 200


 