
hydra:
  run:
    dir: ./
  output_subdir: 

general:
  workdir: ${hydra:runtime.cwd}  # where the code is executed
  datadir: ${general.workdir}/data
  file_path: ${general.workdir}/sample.jpeg

arg:
  newsize1: 200
  newsize2: 200


 